<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_update_projects_alter()
 */
function phpmailer_gmail_oauth2_update_projects_alter(&$projects) {

    // if you want to see phpmailer_gmail_oauth2 in the update status report,
    // you can safely delete this function, or delete this entire file.

    // remove the phpmailer_gmail_oauth2 module from the update status report.
    unset($projects['phpmailer_gmail_oauth2']);
}

/**
 * implements hook_help()
 */
function phpmailer_gmail_oauth2_help(string $route_name, RouteMatchInterface $route_match): ?array {

    $build = [];
    if($route_name === 'help.page.phpmailer_gmail_oauth2') {
        $readme_content = file_get_contents(__DIR__ . '/README.md');
        $build = [
            '#type' => 'html_tag',
            '#tag' => 'pre',
            '#value' => $readme_content,
        ];
    }
    return $build;
}
