phpmailer_gmail_oauth2.settings:
  type: config_object
  label: 'PHPMailer Gmail OAuth2 Settings'
  mapping:
    gm_client_id:
      type: string
      label: 'Gmail Client ID'
    gm_client_secret:
      type: string
      label: 'Gmail Client secret'
    gm_refresh_access_token:
      type: string
      label: 'Gmail Refresh access token'
    gm_provider_url:
      type: string
      label: 'Gmail login Url'
